name: flowly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  appinio_swiper: ^2.1.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/branding.png
    - assets/images/brandingWhite.png
  #   - images/a_dot_ham.jpeg
flutter_native_splash:
  color: "#1E5EFF" # ðŸŽ¨ Your App's Primary Color
  # image: assets/images/logo.png # (Optional) Uncomment if you have a logo file
  image: assets/images/branding.png # (Optional) Bottom branding text image
  
  # Android 12+ specific
  android_12:
    color: "#1E5EFF"
    # icon_background_color: "#ffffff" # Useful if your logo has a background
    # image: assets/images/logo.png 

  # Fullscreen control
  fullscreen: true